### PR TITLE
Fix for Kitty @ 0.24.0

### LINKED ISSUE #25: Does not work with latest kitty@0.24.0
As of kitty version 0.24.0 this is no longer working.

When you try to change panes you get the following error

`module 'kitty.conf.utils' has no attribute 'key_func'`

### PR DESCRIPTION
**Pull request by nickwynja**
Fix #25 with ke.csi_number_for_name

### CODE REVIEW

**Comment by nickwynja** [comment]
Nevermind. I'm seeing now my local version was out of date and this was previously fixed.
