### ISSUE TITLE
Does not work with latest kitty@0.24.0

### ISSUE THREAD

**Issue by anark** [knubie/vim-kitty-navigator#25]
As of kitty version 0.24.0 this is no longer working.

When you try to change panes you get the following error

`module 'kitty.conf.utils' has no attribute 'key_func'`

**Comment by nickwynja** [comment]
This is the commit that removed `key_func`: https://github.com/kovidgoyal/kitty/commit/a26f0419645ef24f6899076f8d326d51c5eaffa0#diff-a6e99e7de9af8f167f660ace0edae178e36d851593df5b53dba84da3e0573f34

Still trying to figure out the fix.

**Comment by nickwynja** [comment]
If you comment out the line `func_with_args, args_funcs = ku.key_func()` in pass_keys.py (which doesn't seem to be called anywhere), I get a new error:

```
kitten pass_keys.py neighboring_window top ctrl+k
module 'kitty.fast_data_types' has no attribute 'GLFW_FKEY_K'
```

**Comment by anark** [comment]
@nickwynja Amazing!  Thank you so much for the quick fix here!
